baseURL = "https://sascribe.com/"
languageCode = "en-us"
title = "Sascribe"

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
ShowReadingTime = true

[menu]
[[menu.main]]
name = "All Reviews"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2
