[build]
  command = "if [ ! -d themes/PaperMod ]; then git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod; fi && hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.146.0"
